### ISSUE TITLE
Log corrupted - restart JVM

### ISSUE THREAD

**Issue by arpittodi** [atomikos/transactions-essentials#35]
Hi,

We are using transaction-essentials 4.0.4 with Spring JTATransactionManager. After keeping JVM running for couple of days, we start getting below exceptions in log file -
Caused by: java.lang.IllegalStateException: could not flush state image Log corrupted - restart JVM com.atomikos.recovery.LogReadException
        at com.atomikos.persistence.imp.StateRecoveryManagerImp.preEnter(StateRecoveryManagerImp.java:54)
        at com.atomikos.finitestates.FSMImp.notifyListeners(FSMImp.java:164)
        at com.atomikos.finitestates.FSMImp.setState(FSMImp.java:251)
        at com.atomikos.icatch.imp.CoordinatorImp.setState(CoordinatorImp.java:312)
        at com.atomikos.icatch.imp.CoordinatorStateHandler.commitFromWithinCallback(CoordinatorStateHandler.java:346)
        at com.atomikos.icatch.imp.ActiveStateHandler$6.doCommit(ActiveStateHandler.java:267)
        at com.atomikos.icatch.imp.CoordinatorStateHandler.commitWithAfterCompletionNotification(CoordinatorStateHandler.java:581)
        at com.atomikos.icatch.imp.ActiveStateHandler.commit(ActiveStateHandler.java:262)
        at com.atomikos.icatch.imp.CoordinatorImp.commit(CoordinatorImp.java:548)
        at com.atomikos.icatch.imp.CoordinatorImp.terminate(CoordinatorImp.java:685)
        at com.atomikos.icatch.imp.CompositeTransactionImp.commit(CompositeTransactionImp.java:282)
        at com.atomikos.icatch.jta.TransactionImp.commit(TransactionImp.java:172)
        ... 56 more

I see same issue being discussed in forum -
https://fogbugz.atomikos.com/defaultc4d2.html?community.6.3467.0

Is fix available in latest version? What is the root cause? Does it have any impact? 

Thanks
Arpit

**Comment by GuyPardon** [comment]
Can you try with 4.0.6? It contains selected ported fixes from the commercial branch.

**Comment by arpittodi** [comment]
After trying 4.0.6, I have started seeing other issue. Which version of JTA is supported with Atomikos Transaction Essentials 4.0.6? JTA 1.0 or JTA 1.1?
As per maven repository dependencies, it requires "geronimo-jta_1.0.1B_spec-1.0.jar".
https://mvnrepository.com/artifact/com.atomikos/transactions-jta/4.0.6

If I use geronimo-jta_1.0.1B_spec-1.0.jar with 4.0.6, I get "NoCLassDefFoundError" for javax.transaction.TransactionSynchronizationRegistry.

**Comment by GuyPardon** [comment]
We offer JTA 1.0. Why do you need the TransactionSynchronizationRegistry?

**Comment by mehdichitforoosh** [comment]
Hi.
I have this problem too with Spring boot 2.1.3 and Atomikos 4.0.6.

**Comment by dhermanns** [comment]
Same Problem here. We are using the spring-boot-atomikos-starter 2.2.4. We experience this error after Upgrading to Spring Boot 2.2. Are there any insights about this?

**Comment by GuyPardon** [comment]
Are you able to share a test project that shows the issue?

**Comment by dhermanns** [comment]
No - but it looks like that the log format changed when migrating from Atomikos 4 to 5, right?
We worked around that by simply changing the atomikos log-directory in our spring properties:

```
spring.jta.atomikos.properties.log-base-dir=./tranlog
```

But of cause it would be smoother if atomikos could handle that on its own...

**Comment by GuyPardon** [comment]
Thanks for the hint. Did that solve the issue for you?

**Comment by dhermanns** [comment]
Yes - it seems to. Maybe that's helpful for others...

**Comment by GuyPardon** [comment]
OK thanks for sharing!
